-- Add ArmaFlex variants sized for the carbon-steel pipe diameters used in the PipeStock catalog.
-- AF series correspond to the manufacturer's wall-thickness variants; 76.1 and 88.9 mm use the listed 76 and 89 mm tubes.
WITH new_items("id","key","categoryKey","categoryLabel","diameter","thickness","type","name","unit","sortOrder") AS (
  VALUES
    ('other-steel-insulation-15-8','OTHER_STEEL_INSULATION_15_8','OTHER','Montážní materiál','15 mm','8 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 15 mm · tloušťka 8 mm — Kaučuková izolace · Uhlíková ocel','m',12119),
    ('other-steel-insulation-15-11-5','OTHER_STEEL_INSULATION_15_11_5','OTHER','Montážní materiál','15 mm','11.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 15 mm · tloušťka 11.5 mm — Kaučuková izolace · Uhlíková ocel','m',12120),
    ('other-steel-insulation-15-14','OTHER_STEEL_INSULATION_15_14','OTHER','Montážní materiál','15 mm','14 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 15 mm · tloušťka 14 mm — Kaučuková izolace · Uhlíková ocel','m',12121),
    ('other-steel-insulation-15-17','OTHER_STEEL_INSULATION_15_17','OTHER','Montážní materiál','15 mm','17 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 15 mm · tloušťka 17 mm — Kaučuková izolace · Uhlíková ocel','m',12122),
    ('other-steel-insulation-15-32','OTHER_STEEL_INSULATION_15_32','OTHER','Montážní materiál','15 mm','32 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 15 mm · tloušťka 32 mm — Kaučuková izolace · Uhlíková ocel','m',12123),
    ('other-steel-insulation-18-8','OTHER_STEEL_INSULATION_18_8','OTHER','Montážní materiál','18 mm','8 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 18 mm · tloušťka 8 mm — Kaučuková izolace · Uhlíková ocel','m',12124),
    ('other-steel-insulation-18-11-5','OTHER_STEEL_INSULATION_18_11_5','OTHER','Montážní materiál','18 mm','11.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 18 mm · tloušťka 11.5 mm — Kaučuková izolace · Uhlíková ocel','m',12125),
    ('other-steel-insulation-18-14','OTHER_STEEL_INSULATION_18_14','OTHER','Montážní materiál','18 mm','14 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 18 mm · tloušťka 14 mm — Kaučuková izolace · Uhlíková ocel','m',12126),
    ('other-steel-insulation-18-17-5','OTHER_STEEL_INSULATION_18_17_5','OTHER','Montážní materiál','18 mm','17.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 18 mm · tloušťka 17.5 mm — Kaučuková izolace · Uhlíková ocel','m',12127),
    ('other-steel-insulation-18-25','OTHER_STEEL_INSULATION_18_25','OTHER','Montážní materiál','18 mm','25 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 18 mm · tloušťka 25 mm — Kaučuková izolace · Uhlíková ocel','m',12128),
    ('other-steel-insulation-18-32','OTHER_STEEL_INSULATION_18_32','OTHER','Montážní materiál','18 mm','32 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 18 mm · tloušťka 32 mm — Kaučuková izolace · Uhlíková ocel','m',12129),
    ('other-steel-insulation-22-8-5','OTHER_STEEL_INSULATION_22_8_5','OTHER','Montážní materiál','22 mm','8.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 22 mm · tloušťka 8.5 mm — Kaučuková izolace · Uhlíková ocel','m',12130),
    ('other-steel-insulation-22-12','OTHER_STEEL_INSULATION_22_12','OTHER','Montážní materiál','22 mm','12 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 22 mm · tloušťka 12 mm — Kaučuková izolace · Uhlíková ocel','m',12131),
    ('other-steel-insulation-22-14-5','OTHER_STEEL_INSULATION_22_14_5','OTHER','Montážní materiál','22 mm','14.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 22 mm · tloušťka 14.5 mm — Kaučuková izolace · Uhlíková ocel','m',12132),
    ('other-steel-insulation-22-18','OTHER_STEEL_INSULATION_22_18','OTHER','Montážní materiál','22 mm','18 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 22 mm · tloušťka 18 mm — Kaučuková izolace · Uhlíková ocel','m',12133),
    ('other-steel-insulation-22-25','OTHER_STEEL_INSULATION_22_25','OTHER','Montážní materiál','22 mm','25 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 22 mm · tloušťka 25 mm — Kaučuková izolace · Uhlíková ocel','m',12134),
    ('other-steel-insulation-22-33-5','OTHER_STEEL_INSULATION_22_33_5','OTHER','Montážní materiál','22 mm','33.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 22 mm · tloušťka 33.5 mm — Kaučuková izolace · Uhlíková ocel','m',12135),
    ('other-steel-insulation-28-8-5','OTHER_STEEL_INSULATION_28_8_5','OTHER','Montážní materiál','28 mm','8.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 28 mm · tloušťka 8.5 mm — Kaučuková izolace · Uhlíková ocel','m',12136),
    ('other-steel-insulation-28-12-5','OTHER_STEEL_INSULATION_28_12_5','OTHER','Montážní materiál','28 mm','12.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 28 mm · tloušťka 12.5 mm — Kaučuková izolace · Uhlíková ocel','m',12137),
    ('other-steel-insulation-28-15-5','OTHER_STEEL_INSULATION_28_15_5','OTHER','Montážní materiál','28 mm','15.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 28 mm · tloušťka 15.5 mm — Kaučuková izolace · Uhlíková ocel','m',12138),
    ('other-steel-insulation-28-19','OTHER_STEEL_INSULATION_28_19','OTHER','Montážní materiál','28 mm','19 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 28 mm · tloušťka 19 mm — Kaučuková izolace · Uhlíková ocel','m',12139),
    ('other-steel-insulation-28-25','OTHER_STEEL_INSULATION_28_25','OTHER','Montážní materiál','28 mm','25 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 28 mm · tloušťka 25 mm — Kaučuková izolace · Uhlíková ocel','m',12140),
    ('other-steel-insulation-28-35','OTHER_STEEL_INSULATION_28_35','OTHER','Montážní materiál','28 mm','35 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 28 mm · tloušťka 35 mm — Kaučuková izolace · Uhlíková ocel','m',12141),
    ('other-steel-insulation-35-9','OTHER_STEEL_INSULATION_35_9','OTHER','Montážní materiál','35 mm','9 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 35 mm · tloušťka 9 mm — Kaučuková izolace · Uhlíková ocel','m',12142),
    ('other-steel-insulation-35-13','OTHER_STEEL_INSULATION_35_13','OTHER','Montážní materiál','35 mm','13 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 35 mm · tloušťka 13 mm — Kaučuková izolace · Uhlíková ocel','m',12143),
    ('other-steel-insulation-35-16','OTHER_STEEL_INSULATION_35_16','OTHER','Montážní materiál','35 mm','16 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 35 mm · tloušťka 16 mm — Kaučuková izolace · Uhlíková ocel','m',12144),
    ('other-steel-insulation-35-19-5','OTHER_STEEL_INSULATION_35_19_5','OTHER','Montážní materiál','35 mm','19.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 35 mm · tloušťka 19.5 mm — Kaučuková izolace · Uhlíková ocel','m',12145),
    ('other-steel-insulation-35-27','OTHER_STEEL_INSULATION_35_27','OTHER','Montážní materiál','35 mm','27 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 35 mm · tloušťka 27 mm — Kaučuková izolace · Uhlíková ocel','m',12146),
    ('other-steel-insulation-35-35','OTHER_STEEL_INSULATION_35_35','OTHER','Montážní materiál','35 mm','35 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 35 mm · tloušťka 35 mm — Kaučuková izolace · Uhlíková ocel','m',12147),
    ('other-steel-insulation-42-9','OTHER_STEEL_INSULATION_42_9','OTHER','Montážní materiál','42 mm','9 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 42 mm · tloušťka 9 mm — Kaučuková izolace · Uhlíková ocel','m',12148),
    ('other-steel-insulation-42-13-5','OTHER_STEEL_INSULATION_42_13_5','OTHER','Montážní materiál','42 mm','13.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 42 mm · tloušťka 13.5 mm — Kaučuková izolace · Uhlíková ocel','m',12149),
    ('other-steel-insulation-42-16-5','OTHER_STEEL_INSULATION_42_16_5','OTHER','Montážní materiál','42 mm','16.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 42 mm · tloušťka 16.5 mm — Kaučuková izolace · Uhlíková ocel','m',12150),
    ('other-steel-insulation-42-20-5','OTHER_STEEL_INSULATION_42_20_5','OTHER','Montážní materiál','42 mm','20.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 42 mm · tloušťka 20.5 mm — Kaučuková izolace · Uhlíková ocel','m',12151),
    ('other-steel-insulation-42-27','OTHER_STEEL_INSULATION_42_27','OTHER','Montážní materiál','42 mm','27 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 42 mm · tloušťka 27 mm — Kaučuková izolace · Uhlíková ocel','m',12152),
    ('other-steel-insulation-42-36-5','OTHER_STEEL_INSULATION_42_36_5','OTHER','Montážní materiál','42 mm','36.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 42 mm · tloušťka 36.5 mm — Kaučuková izolace · Uhlíková ocel','m',12153),
    ('other-steel-insulation-54-9','OTHER_STEEL_INSULATION_54_9','OTHER','Montážní materiál','54 mm','9 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 54 mm · tloušťka 9 mm — Kaučuková izolace · Uhlíková ocel','m',12154),
    ('other-steel-insulation-54-13-5','OTHER_STEEL_INSULATION_54_13_5','OTHER','Montážní materiál','54 mm','13.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 54 mm · tloušťka 13.5 mm — Kaučuková izolace · Uhlíková ocel','m',12155),
    ('other-steel-insulation-54-17','OTHER_STEEL_INSULATION_54_17','OTHER','Montážní materiál','54 mm','17 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 54 mm · tloušťka 17 mm — Kaučuková izolace · Uhlíková ocel','m',12156),
    ('other-steel-insulation-54-21','OTHER_STEEL_INSULATION_54_21','OTHER','Montážní materiál','54 mm','21 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 54 mm · tloušťka 21 mm — Kaučuková izolace · Uhlíková ocel','m',12157),
    ('other-steel-insulation-54-28-5','OTHER_STEEL_INSULATION_54_28_5','OTHER','Montážní materiál','54 mm','28.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 54 mm · tloušťka 28.5 mm — Kaučuková izolace · Uhlíková ocel','m',12158),
    ('other-steel-insulation-54-38','OTHER_STEEL_INSULATION_54_38','OTHER','Montážní materiál','54 mm','38 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 54 mm · tloušťka 38 mm — Kaučuková izolace · Uhlíková ocel','m',12159),
    ('other-steel-insulation-76-1-9-5','OTHER_STEEL_INSULATION_76_1_9_5','OTHER','Montážní materiál','76.1 mm','9.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 76.1 mm · tloušťka 9.5 mm — Kaučuková izolace · Uhlíková ocel','m',12160),
    ('other-steel-insulation-76-1-14','OTHER_STEEL_INSULATION_76_1_14','OTHER','Montážní materiál','76.1 mm','14 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 76.1 mm · tloušťka 14 mm — Kaučuková izolace · Uhlíková ocel','m',12161),
    ('other-steel-insulation-76-1-17-5','OTHER_STEEL_INSULATION_76_1_17_5','OTHER','Montážní materiál','76.1 mm','17.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 76.1 mm · tloušťka 17.5 mm — Kaučuková izolace · Uhlíková ocel','m',12162),
    ('other-steel-insulation-76-1-22','OTHER_STEEL_INSULATION_76_1_22','OTHER','Montážní materiál','76.1 mm','22 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 76.1 mm · tloušťka 22 mm — Kaučuková izolace · Uhlíková ocel','m',12163),
    ('other-steel-insulation-76-1-30','OTHER_STEEL_INSULATION_76_1_30','OTHER','Montážní materiál','76.1 mm','30 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 76.1 mm · tloušťka 30 mm — Kaučuková izolace · Uhlíková ocel','m',12164),
    ('other-steel-insulation-76-1-40-5','OTHER_STEEL_INSULATION_76_1_40_5','OTHER','Montážní materiál','76.1 mm','40.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 76.1 mm · tloušťka 40.5 mm — Kaučuková izolace · Uhlíková ocel','m',12165),
    ('other-steel-insulation-88-9-9-5','OTHER_STEEL_INSULATION_88_9_9_5','OTHER','Montážní materiál','88.9 mm','9.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 88.9 mm · tloušťka 9.5 mm — Kaučuková izolace · Uhlíková ocel','m',12166),
    ('other-steel-insulation-88-9-14-5','OTHER_STEEL_INSULATION_88_9_14_5','OTHER','Montážní materiál','88.9 mm','14.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 88.9 mm · tloušťka 14.5 mm — Kaučuková izolace · Uhlíková ocel','m',12167),
    ('other-steel-insulation-88-9-18','OTHER_STEEL_INSULATION_88_9_18','OTHER','Montážní materiál','88.9 mm','18 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 88.9 mm · tloušťka 18 mm — Kaučuková izolace · Uhlíková ocel','m',12168),
    ('other-steel-insulation-88-9-22-5','OTHER_STEEL_INSULATION_88_9_22_5','OTHER','Montážní materiál','88.9 mm','22.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 88.9 mm · tloušťka 22.5 mm — Kaučuková izolace · Uhlíková ocel','m',12169),
    ('other-steel-insulation-88-9-30-5','OTHER_STEEL_INSULATION_88_9_30_5','OTHER','Montážní materiál','88.9 mm','30.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 88.9 mm · tloušťka 30.5 mm — Kaučuková izolace · Uhlíková ocel','m',12170),
    ('other-steel-insulation-88-9-41-5','OTHER_STEEL_INSULATION_88_9_41_5','OTHER','Montážní materiál','88.9 mm','41.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 88.9 mm · tloušťka 41.5 mm — Kaučuková izolace · Uhlíková ocel','m',12171),
    ('other-steel-insulation-108-9-5','OTHER_STEEL_INSULATION_108_9_5','OTHER','Montážní materiál','108 mm','9.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 108 mm · tloušťka 9.5 mm — Kaučuková izolace · Uhlíková ocel','m',12172),
    ('other-steel-insulation-108-14-5','OTHER_STEEL_INSULATION_108_14_5','OTHER','Montážní materiál','108 mm','14.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 108 mm · tloušťka 14.5 mm — Kaučuková izolace · Uhlíková ocel','m',12173),
    ('other-steel-insulation-108-18','OTHER_STEEL_INSULATION_108_18','OTHER','Montážní materiál','108 mm','18 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 108 mm · tloušťka 18 mm — Kaučuková izolace · Uhlíková ocel','m',12174),
    ('other-steel-insulation-108-23','OTHER_STEEL_INSULATION_108_23','OTHER','Montážní materiál','108 mm','23 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 108 mm · tloušťka 23 mm — Kaučuková izolace · Uhlíková ocel','m',12175),
    ('other-steel-insulation-108-31','OTHER_STEEL_INSULATION_108_31','OTHER','Montážní materiál','108 mm','31 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 108 mm · tloušťka 31 mm — Kaučuková izolace · Uhlíková ocel','m',12176),
    ('other-steel-insulation-108-42-5','OTHER_STEEL_INSULATION_108_42_5','OTHER','Montážní materiál','108 mm','42.5 mm','Kaučuková izolace · Uhlíková ocel','Montážní materiál 108 mm · tloušťka 42.5 mm — Kaučuková izolace · Uhlíková ocel','m',12177)
)
INSERT INTO "material_catalog_items" (
  "id","key","categoryKey","categoryLabel","diameter","thickness","type","name","unit","sortOrder","isActive","updatedAt"
)
SELECT "id","key","categoryKey","categoryLabel","diameter","thickness","type","name","unit","sortOrder",true,CURRENT_TIMESTAMP
FROM new_items
ON CONFLICT ("key") DO UPDATE SET
  "categoryKey" = EXCLUDED."categoryKey",
  "categoryLabel" = EXCLUDED."categoryLabel",
  "diameter" = EXCLUDED."diameter",
  "thickness" = EXCLUDED."thickness",
  "type" = EXCLUDED."type",
  "name" = EXCLUDED."name",
  "unit" = EXCLUDED."unit",
  "sortOrder" = EXCLUDED."sortOrder",
  "isActive" = true,
  "updatedAt" = CURRENT_TIMESTAMP;
